from enum import IntEnum

# VISION

VISION_WIDTH = 128
VISION_HEIGHT = 128
VISION_COLOUR_CHANNELS = 3


VISION_OUT_LEN = 32

VISION_CONV_CHANNELS = (16, 24, 32, 48)
VISION_KERNEL_SIZES = (5, 3, 3, 3)
VISION_STRIDES = (2, 2, 2, 2)
VISION_PADDINGS = (2, 1, 1, 1)
VISION_HIDDEN_SIZE = 128

# ACTOR HEAD


class DogModelTarget(IntEnum):
    TUNNEL = 0
    RAMP = 1
    BLOCK = 2
    TILE = 3


ACTOR_HIDDEN_SIZE = 64


class DogModelAction(IntEnum):
    FORWARD = 1
    BACKWARD = 2
    LEFT = 3
    RIGHT = 4
